variables:
    GIT_DEPTH: "1"

stages:
    - mil-internal-release_build
    - prepare_mil-internal-release_debs

mil-internal-release_build:
    tags:
        - Runner-Stretch
    stage: mil-internal-release_build
    script:
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20200211 stretch main" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install -y -qq --no-install-recommends build-essential devscripts linux-headers-4.9.0-12-amd64
        - apt-get build-dep ./ -y
        - dpkg-buildpackage -us -uc -b
        - mv ../*.buildinfo .
        - mv ../*.changes .
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.buildinfo
        - ./*.changes
        - ./*.deb

prepare_mil-internal-release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_mil-internal-release_debs
    only:
      refs:
        - stretch/master
    dependencies:
        - mil-internal-release_build
    when: manual
    script:
        - mkdir -p /cache/stretch/mil-internal-release/
        - cp *.deb /cache/stretch/mil-internal-release/
        - ls /cache/stretch/mil-internal-release/
